[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
description = "Simracing Virtual Mentor Yew bootstrap project using Trunk"
readme = "README.md"

[dependencies]
yew = {  version = "0.21", features = ["csr"] }
yew-hooks = "0.3.1"
plotly = { version = "0.8.4", features = ["wasm"] }
wasm-bindgen = "0.2.92"
wasm-logger = "0.2.0"
shared = {path = "../shared"}