services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 16666:16666
    environment:
      BACKEND__SERVER__HOST: 0.0.0.0
      BACKEND__SERVER__PORT: 16666
      BACKEND__EVENT_BUS_CAPACITY: 200
      BACKEND__LOG_LEVEL: DEBUG