server:
  host: 0.0.0.0
  port: 16666
event_bus:
  capacity: 200
log_level: trace
mongo:
  uri: mongodb://localhost:27017
  database: symracing_virtual_mentor
  collections:
    analysis: analysis
    file: file
    lap: lap
  user: admin
  pass: 1234
fcm_grid:
  c:
    init: 3
    max: 7
    inc: 1
  m:
    init: 1.7
    max: 2.5
    inc: 0.1
  max_iter:
    init: 100
  error:
    init: 0.01