[package]
name = "symracing_virtual_mentor_shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2.0"
uuid = { version = "1.13", features = ["v4", "serde"] }
serde_json = "1.0"
ndarray = "0.16"
ndarray-rand = "0.15"
rand = "0.8"

[dev-dependencies]
mockall = "0.13"
tokio = { version = "1.43", features = ["test-util"] }